---
version: "3.8"
services:
    build_les7:
        build:
            context: .
            dockerfile: ./build/Dockerfile
        volumes:
            - type: volume
              source: artifacts
              target: /tmp/boxfuse-sample-java-war-hello/target

    prod_les7:
        build:
            context: .
            dockerfile: ./prod/Dockerfile
        ports:
            - "8088:8080"
        volumes: 
            - type: volume
              source: artifacts
              target: /usr/local/tomcat/webapps
              volume:
                  nocopy: true


volumes: 
    artifacts:
---